#!/usr/bin/env python
"""Rewrite the input-authority table in control_research/program.md from
figs/pi_gains.json, so the agent's briefing carries the current dataset's
numbers and not a previous plant's."""
from __future__ import annotations

import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
g = json.loads((ROOT / "figs" / "pi_gains.json").read_text())
cv, mv, A = g["cv"], g["mv"], g["authority_sigma"]

rows = ["|            | " + " | ".join(cv) + " |", "|---|" + "---|" * len(cv)]
for i, m in enumerate(mv):
    best = max(range(len(cv)), key=lambda j: A[i][j])
    cells = [f"**{A[i][j]:.2f}**" if j == best and A[i][j] >= 1.0 else f"{A[i][j]:.2f}"
             for j in range(len(cv))]
    rows.append(f"| {m:<15s} | " + " | ".join(cells) + " |")
table = "\n".join(rows)

p = ROOT / "control_research" / "program.md"
s = p.read_text()
pat = re.compile(r"(identification data; regenerated by `scripts/identify_pi.py`\):\n\n)(\|.*?\n)(?:\|.*?\n)+", re.S)
m = pat.search(s)
assert m, "table anchor not found"
s = s[:m.start(2)] + table + "\n" + s[m.end():]
L = g["dead_time_s"]
s = re.sub(r"\n\*\*Measured dead times\*\*.*?\n\n", "\n", s, flags=re.S)
s = s.replace(table + "\n", table + "\n\n**Measured dead times** (cross-correlation of increments): "
              + ", ".join(f"{k} {v} s" for k, v in L.items()) + "\n\n", 1)
p.write_text(s)
print(table); print("dead times:", L); print("-> program.md updated")
